---
- name: Connect to SharePoint and Fetch Documents
  hosts: localhost
  gather_facts: no
  vars:
    sharepoint_url: "https://ascendionhub.sharepoint.com/sites/PlatformSupportCommunity823-Team-Docs"
    document_library: "Shared Documents"
    download_folder: "/tmp/sharepoint_files"
    username: "akhil.tanguturu@ascendion.com"
    password: "Balavenkatasubbaiah@2002"

  tasks:
    - name: Ensure download directory exists
      ansible.builtin.file:
        path: "{{ download_folder }}"
        state: directory
        mode: '0755'

    - name: Fetch SharePoint Access Token (Basic Auth)
      ansible.builtin.uri:
        url: "{{ sharepoint_url }}/_api/web/lists/getbytitle('{{ document_library }}')/items"
        method: GET
        user: "{{ username }}"
        password: "{{ password }}"
        force_basic_auth: yes
        return_content: yes
        headers:
          Accept: "application/json;odata=verbose"
      register: sharepoint_files

    - name: Display SharePoint Files
      debug:
        var: sharepoint_files.json.d.results

    - name: Download Files from SharePoint
      ansible.builtin.get_url:
        url: "{{ item['FileRef']['__deferred']['uri'] }}"
        dest: "{{ download_folder }}/{{ item['FileLeafRef'] }}"
        url_username: "{{ username }}"
        url_password: "{{ password }}"
        force_basic_auth: yes
      loop: "{{ sharepoint_files.json.d.results }}"
      when: "'FileLeafRef' in item"
